language: 'node_js'
node_js: '8'

before_script:
  - npm run lint
  - npm run generate
  - cp ./dist/index.html ./dist/404.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  repo: christopherkade/Jammer
  target_branch: gh-pages
  on:
    branch: master
